version: "3.4"

services:
    db:
        image: postgres:9.6.9-alpine
        container_name: db
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

    uri-checker-worker:
        image: python:3.6-alpine
        container_name: uri-checker-worker
        volumes:
            - ./src:/src
        command: python /src/uri-check-worker.py http://yahoo.com