version: "3.4"

services:

    uri-check-worker:
        build: ./src
        container_name: uri-check-worker
        volumes:
            - ./src:/src
        command: python -u /src/uri-check-worker.py http://yahoo.com
